### PR TITLE
Patch add title

### LINKED ISSUE #8: Option to include topic title at end of message title
When enabled:
> Post Approval Request for [Category]: [Name of Topic]

When disabled: (default)
> Post Approval Request for [Category]

### PR DESCRIPTION
**Pull request by buildthomas**
Fixes #8

### CODE REVIEW

**Comment by buildthomas** [comment]
Pls test and review, big thanks

**Comment by Kampfkarren** [comment]
Did you actually test the new spec? Put this in your terminal:

```
bundle exec rake plugin:spec["new-member-redirect"]
```

**Comment by buildthomas** [comment]
Would you be able to run the spec? I haven't been able to set up a test environment yet.

**Comment by Kampfkarren** [comment]
Tests passed!

**Pull request merged**
